definitions:
  model.Address:
    properties:
      city:
        type: string
      country:
        type: string
      id:
        type: string
      state:
        type: string
      street:
        type: string
      zip_code:
        type: string
    type: object
  model.School:
    properties:
      address_id:
        type: string
      code:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: School Ride Backend Server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/addresses/:
    get:
      description: Retrieves a list of all addresses
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Get all addresses
      tags:
      - addresses
    post:
      consumes:
      - application/json
      description: Creates a new address with the provided details
      parameters:
      - description: Address details
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/model.Address'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new address
      tags:
      - addresses
  /api/v1/schools/:
    get:
      description: Get all schools
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - Schools
    post:
      description: Create a new school
      parameters:
      - description: School object
        in: body
        name: school
        required: true
        schema:
          $ref: '#/definitions/model.School'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/model.School'
            type: array
      tags:
      - Schools
  /healthz/ping:
    get:
      description: Responds with a simple message to indicate the service is running
      produces:
      - application/json
      responses:
        "200":
          description: pong response
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check endpoint
      tags:
      - health
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
